version: "3.7"

services:
  prometheus:
    image: prom/prometheus
    network_mode: "host"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    network_mode: "host"
    volumes:
        - ./grafana/provisioning/:/etc/grafana/provisioning/
        - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
