global:
  scrape_interval: 1s

scrape_configs:
- job_name: zeebe
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - localhost:8080
    - localhost:8081
    - localhost:8082
