{
 "title": "Client Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(zeebe_benchmark_instancePartition_total, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "content": "# Production - S\n\n- **Partitions**: 1\n- **Replication Factor**: 3\n- **CPU**: 1\n- **RAM**: 2GiB"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "content": "# Production - M\n\n- **Partitions**: 4\n- **Replication Factor**: 3\n- **CPU**: 4\n- **RAM**: 8GiB"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "content": "# Production - L\n\n- **Partitions**: 8\n- **Replication Factor**: 3\n- **CPU**: 8\n- **RAM**: 16GiB"
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Instances/s",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_benchmark_instances_total[10s])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Jobs Instances/s",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(zeebe_benchmark_jobs_total[10s])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Instances/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(zeebe_benchmark_instancePartition_total{namespace=~\"$namespace\"}[10s])",
       "legendFormat": "{{partitionId}}"
      }
     ]
    },
    {
     "title": "Jobs/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(zeebe_benchmark_jobPartition_total{namespace=~\"$namespace\"}[10s])",
       "legendFormat": "{{partitionId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Instance Partitions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_benchmark_instancePartition_total{namespace=~\"$namespace\"}",
       "legendFormat": "{{partitionId}}"
      }
     ]
    },
    {
     "title": "Job Partitions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_benchmark_jobPartition_total{namespace=~\"$namespace\"}",
       "legendFormat": "{{partitionId}}"
      }
     ]
    }
   ]
  }
 ]
}