{
 "title": "Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(zeebe_health, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "FNI/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{action=\"completed\", type!=\"PROCESS\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(rate(zeebe_element_instance_events_total{action=\"completed\", type!=\"PROCESS\", namespace=\"$namespace\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", pod_name!~\".*curator.*\", cluster=\"\", namespace=\"$namespace\", image!=\"\", container_name!=\"POD\"}[1m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zeebe_running_workflow_instances_total{namespace=\"$namespace\"}) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}} - RSS"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\"}) by (pod, area)",
     "legendFormat": "{{pod}} - JVM {{area}}"
    }
   ]
  },
  {
   "title": "Used PVC Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"$namespace\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Used PVC Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum((kubelet_volume_stats_used_bytes{namespace=\"$namespace\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zeebe_received_request_count_total{namespace=\"$namespace\"}[1m]) - rate(zeebe_dropped_request_count_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Handled"
    },
    {
     "expr": "sum(rate(zeebe_received_request_count_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "ALL - received"
    },
    {
     "expr": "sum(rate(zeebe_dropped_request_count_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "ALL - dropped"
    },
    {
     "expr": "sum(rate(zeebe_dropped_request_count_total{namespace=\"$namespace\"}[1m])) by (partition)",
     "legendFormat": "{{partition}} - dropped"
    },
    {
     "expr": "sum(rate(zeebe_received_request_count_total{namespace=\"$namespace\"}[1m])) by (partition)",
     "legendFormat": "{{partition}} - received"
    }
   ]
  }
 ]
}